ticks_per_sec: 60
total_maps: 5
maps:
  0: "../mapa1.yaml"
  1: "../mapa2.yaml"
  2: "../mapa3.yaml"
  3: "../mapa4.yaml"
  4: "../mapa5.yaml"
speedFactor: 1
blockMovement: 1
rangeFactor: 2000
timeFactor: 1
initialGold: 10000
initialEnergy: 2500
initialMaxEnergy: 5000
# esta en /Dune/utils/Enunciado.pdf
buildings:
  constructionTime: 100
  constructionCenter:
    energy: 0
    cost: 0
    hitPoints: 3000
    width: 3
    height: 3
  windTrap:
    energy: 500
    cost: 800
    hitPoints: 500
    width: 3
    height: 3
  lightFactory:
    energy: 500
    cost: 800
    hitPoints: 500
    width: 3
    height: 3
  heavyFactory:
    energy: 800
    cost: 1500
    hitPoints: 1500
    width: 4
    height: 4
  refinery:
    energy: 400
    cost: 500
    hitPoints: 500
    spiceCapacity: 5000
    width: 3
    height: 3
  silo:
    energy: 100
    cost: 200
    hitPoints: 200
    spiceCapacity: 1000
    width: 1
    height: 1
  barracks:
    energy: 100
    cost: 300
    hitPoints: 300
    width: 3
    height: 2
weaponry:
  assaultRifle:
    damage: 2
    shootingRate: 6
    bonus: 1
  cannon:
    damage: 7
    shootingRate: 1
    bonus: 0
  rocketLauncher:
    damage: 8
    shootingRate: 1
    bonus: 0
  smallCannon:
    damage: 6
    shootingRate: 6
    bonus: 2
units:
  lightInfantry:
    hitPoints: 50
    range: 3
    speed: 16
    trainingTime: 60
    cost: 50
  heavyInfantry:
    hitPoints: 80
    range: 3
    speed: 12
    trainingTime: 78
    cost: 70
  harvester:
    hitPoints: 600
    speed: 12
    trainingTime: 180
    cost: 300
    spiceCapacity: 200
    farmSpeed: 20
    loadSpeed: 5
  trike:
    hitPoints: 80
    range: 4
    speed: 64
    trainingTime: 120
    cost: 100
  raider:
    hitPoints: 80
    range: 4
    speed: 84
    trainingTime: 120
    cost: 100
  tank:
    hitPoints: 30
    range: 4
    speed: 40
    trainingTime: 240
    cost: 300
